import'./index.css'
export default function App(){
    return(
        <div>
            <h1>MANIKANDAN</h1>
           <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Voluptas quasi quod, reiciendis vitae fuga repellendus sapiente eaque illo cum dolores animi expedita beatae est corrupti officia illum, neque sint labore provident sed. Iste velit ut pariatur expedita a ducimus numquam! Temporibus atque quis necessitatibus fugit? Animi, nisi eligendi. Sequi laborum dicta eos odit minus non, officiis facilis ipsum doloribus deserunt similique accusantium beatae porro distinctio praesentium quod? Fugit repudiandae, dolores consequatur optio inventore voluptatum est, dolorum vero obcaecati veritatis quis doloremque eos nemo. Vel hic consectetur quas iste enim voluptates qui laborum similique delectus ratione culpa magni a in illum architecto quia molestias ab esse atque ullam beatae nobis, vero, quod autem! Vero nostrum alias ipsam beatae, doloremque in aut! Harum placeat ipsam aperiam quaerat quasi, dolore quod necessitatibus quidem ea numquam ratione impedit, magnam quas beatae amet facilis cumque totam suscipit consectetur sequi? Dolore nihil, incidunt similique quo, exercitationem sed nobis enim illum explicabo voluptates adipisci facere expedita quaerat natus impedit placeat deleniti aliquam nisi labore corrupti eius voluptatem eos repellendus! Eveniet dolores veniam fuga id voluptate tempora illum earum exercitationem doloribus velit laudantium quam voluptatem alias, amet ea officia sapiente saepe, praesentium sed labore animi repudiandae quidem odio similique. Iste illum nostrum cupiditate numquam quaerat perferendis! Consequuntur iste quidem soluta iusto laboriosam illum facilis voluptatum at? Eveniet praesentium nesciunt repellendus porro numquam delectus accusamus. Optio dolores necessitatibus odio esse asperiores dolorum ex corrupti ratione voluptate vero repellendus architecto ipsum laudantium maiores sapiente at et quisquam doloribus reiciendis animi quia voluptas sit, quasi eos. Expedita consequatur ullam, modi dolores tempore eius velit maxime molestias. Nobis officia, sit repellendus velit ipsam, quaerat, suscipit consectetur vel atque quibusdam dolore expedita rerum voluptate unde dolor quos minus perspiciatis. Quod, sequi praesentium, incidunt ad assumenda inventore voluptatem suscipit fugit quos autem odio culpa.</p>
        </div>
    )
}

